### ISSUE TITLE
admin.local on port 8080

### ISSUE THREAD

**Issue by pieterhoekstra** [DEAN-ngo/elimupi#34]
In files/nginx/admin.local the server listens on a different port 8080. Is there a reason for this?

**Comment by ltoning** [comment]
Hi @pieterhoekstra @joostdam 

Changed Nginx web config admin.local so that http://kolibri.elimupi.online is listening on port 80 instead of port 8080. This will be needed in advance to start using https and and signed certificate.
Accordingly there is a need to adjust de webcontent related files:

[https://github.com/DEAN-ngo/ElimuPi-Web-Interface/blob/main/index.php](https://github.com/DEAN-ngo/ElimuPi-Web-Interface/blob/main/index.php
)
[https://github.com/DEAN-ngo/ElimuPi-Web-Interface/blob/main/php/includes/resource.inc.php](https://github.com/DEAN-ngo/ElimuPi-Web-Interface/blob/main/php/includes/resource.inc.php
)

I don't have full access to this repo can someone else make the changes?

**Comment by ltoning** [comment]
Nginx vhost  config admin.local is now using http on port 80 en redirects vhost servername http://admin.elimupi.online to http://start.elimupi.online/admin/?lang=.

**Comment by pieterhoekstra** [comment]
Hoi Laurens,

Bedankt voor het afhandelen van dit ticket. Ik zal de webinterface updaten
met de gewone poort,

Pieter

Op di 19 jul. 2022 13:36 schreef Laurens Töning ***@***.***>:
